# Generated by Django 2.2.19 on 2023-01-20 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_auto_20230118_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="описание"
            ),
            preserve_default=False,
        ),
    ]
